<?php

namespace App\Http\Requests\Transaction;

use Illuminate\Foundation\Http\FormRequest;

class ProcessPaymentRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'card_id' => 'required|integer|exists:cards,id',
            'amount' => 'required|numeric|min:0.01',
            'currency' => 'required|string|size:3',
            'merchant_name' => 'required|string',
            'cryptogram' => 'required|string', // The token generated by HCE
        ];
    }
}
